---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: todo-api-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCCqmGwFyVJfN829zZB1oExPoBT1FCeCrHd5DfwZ3qoNKp1E+42g2NjKoFPL2zUID2gUeC1Gniti3ruqTxqLdjRsQAnOUyM5/12SDWbH8j9WEOllJTI/qihynbUH9iZWZMtRUlfCprBqpJnEjFjKLbMhFU6lhHkG1aTAAwuxVqczicDXWbdxxrP9wappdI1vTiJK6Cf7Vqc3JxDwIwLRC65+Ajmow2SqgGvdhUW6toBZQYePSBT1bPsbvuTnJsderMkMFmsfHauPn73wKU2O+bn/hp5ow00DF2pDuFjg8d5eOXRv6zVzkRZ3a8gl+teVBvVbldpF6tGlWYYlhN3CfOZj9421nT/WJ0839jwb/Cu8H4+B7WJqsIjsNDZ51DAwPuz9jqTGjzd7/wi16EqH/xz/NgHeGtZnPDc7+ifPz3f1IBLnjO1ARS4sMezZi9bowf+V+7FCE1WeiRegqkNpyrsdDUQ5g/CQkHcx34ljC+ewe/W1nifADToEyIJfuh/Q9nlN3e+bUMbw1fgGOSxN5xnrrh5BX976DQESEK6Jz8YfHw2chckWQCE6xlOeWdv7mcS8+QRtBhDTcSG7R6bQFn8NoY4+j7t0H2v0onGbNrJyb2rSu/w33cttoQBjaLldFk8KPQLjXRiRgu+4eE8TPv5CTSXhxORAz1sAcF6nzWg6Aa7XDwFFPAhvm53D1bTTHF/meLdlNr8WMYPeT3y4Box3bc8tzaxkOJsKu5YOOoQmxu+aGGCa9aTXQbhlUiJuV+HAbbm6stMT/7MaM80rHme1od8gKqZRUEMLmgqzHbcR4PgRWj41/svmYvSAozuteIMobvI5XNjNS1ZlYI04FXJ9V06UvL2MpRoleFDDR+DUuhSDlqaNUUm9xomXXag9hAGPwofCkHl6Jp2PPh2WbwsG1uwN3TkX9Wr6vdxXqG6SXGRZIop0n7vCfDSP46kyyMpf3soM4+hM3KIX106CfxJn4OR04U=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: todo-api-dev
    type: kubernetes.io/dockerconfigjson
