apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-team-eiffage
  namespace: infra-system
spec:
  interval: 1m
  url: https://github.com/projets-sdv/gitops-team-eiffage.git
  ref:
    branch: main
